# Retail Business Analysis

## Business Context

The company wants to understand its commercial performance across 2025–2026, identify the main drivers of its results, and detect areas that require further investigation.

This analysis will focus on understanding the available transactional data before developing specific business hypotheses.

In [1]:
import pandas as pd

In [2]:
import os

os.getcwd()

'c:\\Users\\alopez\\Desktop\\Alexis LAVARTEX\\VS\\analytics-retail\\notebooks'

In [3]:
df = pd.read_csv('../data/raw/retail_transactions.csv')

In [4]:
df.head()

,transaction_id,transaction_date,customer_id,customer_segment,region,channel,product_id,category,units,unit_price,discount_pct,payment_method,gross_revenue,net_revenue
0,T0020861,2026-11-01,C0222,Consumer,South,Store,P096,Home,1,64.06,0.05,Card,64.06,60.86
1,T0018393,2025-06-01,C0590,Consumer,West,Store,P026,Electronics,1,560.80,0.00,Card,560.80,560.80
2,T0021225,2026-10-24,C0827,SMB,South,Online,P105,Sports,4,71.92,0.25,Cash,287.68,215.76
3,T0021172,2025-04-18,C0130,SMB,North,Store,P033,Sports,6,159.94,0.00,Digital Wallet,959.64,959.64
4,T0004284,2025-11-15,C0234,SMB,West,Marketplace,P073,Office,1,96.37,0.00,Transfer,96.37,96.37

In [5]:
print(df.shape)
print(df.columns)
print(df.dtypes)

(28018, 14)
Index(['transaction_id', 'transaction_date', 'customer_id', 'customer_segment',
       'region', 'channel', 'product_id', 'category', 'units', 'unit_price',
       'discount_pct', 'payment_method', 'gross_revenue', 'net_revenue'],
      dtype='str')
transaction_id          str
transaction_date        str
customer_id             str
customer_segment        str
region                  str
channel                 str
product_id              str
category                str
units                 int64
unit_price          float64
discount_pct        float64
payment_method          str
gross_revenue       float64
net_revenue         float64
dtype: object

In [6]:
df['transaction_id'].nunique()

28000

In [7]:
df[df['transaction_id'].duplicated(keep=False)]

,transaction_id,transaction_date,customer_id,customer_segment,region,channel,product_id,category,units,unit_price,discount_pct,payment_method,gross_revenue,net_revenue
424,T0000906,2025-03-15,C0306,Consumer,North,Marketplace,P058,Personal Care,2,37.03,0.05,Card,74.06,70.36
721,T0000879,2026-03-23,C0385,Consumer,North,Store,P002,Personal Care,2,59.31,0.00,Card,118.62,118.62
942,T0008607,2026-05-10,C0143,Corporate,South,Online,P097,Office,3,121.68,0.15,Card,365.04,310.28
1296,T0000755,2025-10-24,C0087,SMB,West,Online,P076,Office,2,37.18,0.00,Digital Wallet,74.36,74.36
2078,T0009119,2025-03-19,C0199,Consumer,West,Online,P063,Electronics,4,412.44,0.00,Transfer,1649.76,1649.76
3111,T0013112,2025-12-09,C0448,SMB,North,Online,P092,Home,7,58.02,0.20,Card,406.14,324.91
3340,T0009119,2025-03-19,C0199,Consumer,West,Online,P063,Electronics,4,412.44,0.00,Transfer,1649.76,1649.76
3960,T0008812,2026-10-24,C0543,SMB,North,Online,P108,Office,3,123.87,0.00,Card,371.61,371.61
6021,T0019748,2026-03-12,C0849,Consumer,West,Online,P096,Home,1,64.96,0.25,Card,64.96,48.72
6747,T0027253,2025-02-19,C0439,SMB,Central,Online,P107,Electronics,3,330.66,0.00,Cash,991.98,991.98
8512,T0013112,2025-12-09,C0448,SMB,North,Online,P092,Home,7,58.02,0.20,Card,406.14,324.91
9404,T0021563,2025-11-04,C0185,SMB,Central,Store,P015,Home,5,59.44,0.00,Digital Wallet,297.20,297.20
9454,T0008812,2026-10-24,C0543,SMB,North,Online,P108,Office,3,123.87,0.00,Card,371.61,371.61
10779,T0022587,2026-10-13,C0388,Corporate,Central,Store,P059,Personal Care,6,63.46,0.10,Transfer,380.76,342.68
11524,T0013042,2026-10-11,C0782,Corporate,West,Marketplace,P077,Sports,3,205.94,0.00,Transfer,617.82,617.82
13567,T0026555,2025-11-12,C0253,Consumer,South,Store,P003,Home,1,140.44,0.10,Transfer,140.44,126.40
14183,T0000879,2026-03-23,C0385,Consumer,North,Store,P002,Personal Care,2,59.31,0.00,Card,118.62,118.62
14221,T0018216,2025-06-26,C0382,Corporate,Central,Online,P043,Electronics,4,872.36,0.00,Cash,3489.44,3489.44
14930,T0022587,2026-10-13,C0388,Corporate,Central,Store,P059,Personal Care,6,63.46,0.10,Transfer,380.76,342.68
15070,T0010486,2026-07-14,C0587,Consumer,North,Store,P093,Electronics,4,825.49,0.20,Card,3301.96,2641.57
15632,T0018216,2025-06-26,C0382,Corporate,Central,Online,P043,Electronics,4,872.36,0.00,Cash,3489.44,3489.44
15917,T0000906,2025-03-15,C0306,Consumer,North,Marketplace,P058,Personal Care,2,37.03,0.05,Card,74.06,70.36
16238,T0008607,2026-05-10,C0143,Corporate,South,Online,P097,Office,3,121.68,0.15,Card,365.04,310.28
16316,T0021563,2025-11-04,C0185,SMB,Central,Store,P015,Home,5,59.44,0.00,Digital Wallet,297.20,297.20
16591,T0019748,2026-03-12,C0849,Consumer,West,Online,P096,Home,1,64.96,0.25,Card,64.96,48.72
16700,T0026555,2025-11-12,C0253,Consumer,South,Store,P003,Home,1,140.44,0.10,Transfer,140.44,126.40
18614,T0023816,2025-11-18,C0177,Consumer,West,Store,P089,Personal Care,1,98.94,0.00,Cash,98.94,98.94
19465,T0013042,2026-10-11,C0782,Corporate,West,Marketplace,P077,Sports,3,205.94,0.00,Transfer,617.82,617.82
21200,T0000755,2025-10-24,C0087,SMB,West,Online,P076,Office,2,37.18,0.00,Digital Wallet,74.36,74.36
21816,T0023816,2025-11-18,C0177,Consumer,West,Store,P089,Personal Care,1,98.94,0.00,Cash,98.94,98.94
22970,T0019598,2026-11-25,C0308,SMB,North,Store,P090,Electronics,3,766.70,0.10,Transfer,2300.10,2070.09
23635,T0002141,2026-01-22,C0220,Consumer,Central,Online,P038,Electronics,3,326.23,0.15,Cash,978.69,831.89
25197,T0010486,2026-07-14,C0587,Consumer,North,Store,P093,Electronics,4,825.49,0.20,Card,3301.96,2641.57
25661,T0027253,2025-02-19,C0439,SMB,Central,Online,P107,Electronics,3,330.66,0.00,Cash,991.98,991.98
26645,T0002141,2026-01-22,C0220,Consumer,Central,Online,P038,Electronics,3,326.23,0.15,Cash,978.69,831.89
27650,T0019598,2026-11-25,C0308,SMB,North,Store,P090,Electronics,3,766.70,0.10,Transfer,2300.10,2070.09

In [8]:
df.duplicated().sum()

np.int64(18)

In [9]:
df.isna().sum()

transaction_id       0
transaction_date     0
customer_id          0
customer_segment    38
region              27
channel              0
product_id           0
category             0
units                0
unit_price           0
discount_pct         0
payment_method      31
gross_revenue        0
net_revenue          0
dtype: int64

In [10]:
null_percent = (df.isna().sum() / len(df) * 100).sort_values(ascending=False).rename('null_percentage')
null_percent

customer_segment    0.135627
payment_method      0.110643
region              0.096367
transaction_date    0.000000
customer_id         0.000000
transaction_id      0.000000
channel             0.000000
product_id          0.000000
units               0.000000
category            0.000000
unit_price          0.000000
discount_pct        0.000000
gross_revenue       0.000000
net_revenue         0.000000
Name: null_percentage, dtype: float64

In [11]:
df.loc[df['customer_segment'].isna(),['customer_id', 'customer_segment', 'region', 'transaction_date']]

      customer_id customer_segment   region transaction_date
643         C0523              NaN  Central       2026-10-15
1217        C0754              NaN    South       2026-05-22
1336        C0449              NaN    South       2026-01-05
1460        C0797              NaN  Central       2026-11-13
3982        C0321              NaN  Central       2026-08-26
5447        C0753              NaN    South       2025-03-20
5771        C0737              NaN  Central       2026-12-28
6882        C0279              NaN    South       2025-11-07
6919        C0088              NaN    North       2025-12-06
9922        C0042              NaN     West       2026-11-24
10839       C0774              NaN    North       2026-05-31
12231       C0211              NaN     West       2025-12-18
13047       C0429              NaN     West       2026-08-21
13385       C0457              NaN  Central       2026-06-01
13553       C0327              NaN  Central       2025-06-22
14446       C0203              NaN  Central       2026-06-22
14691       C0818              NaN  Central       2025-11-15
15316       C0120              NaN    North       2026-03-07
15430       C0645              NaN  Central       2026-01-28
15515       C0367              NaN  Central       2026-10-05
16375       C0342              NaN  Central       2026-03-09
16831       C0680              NaN  Central       2025-11-30
17374       C0235              NaN     West       2025-06-18
17889       C0297              NaN    South       2025-08-06
18711       C0533              NaN  Central       2025-08-02
18760       C0030              NaN  Central       2025-05-15
19282       C0226              NaN  Central       2026-11-19
20284       C0302              NaN     West       2025-10-01
22591       C0846              NaN  Central       2026-01-17
22915       C0705              NaN  Central       2025-12-02
24036       C0101              NaN  Central       2026-05-22
24347       C0558              NaN    North       2025-09-06
25742       C0221              NaN     West       2025-12-04
26272       C0171              NaN     West       2026-03-19
26531       C0141              NaN    South       2026-03-10
27088       C0328              NaN  Central       2025-10-05
27400       C0667              NaN    North       2026-12-24
27447       C0027              NaN  Central       2026-01-18

In [12]:
df[df['customer_id'] == 'C0523']

,transaction_id,transaction_date,customer_id,customer_segment,region,channel,product_id,category,units,unit_price,discount_pct,payment_method,gross_revenue,net_revenue
643,T0016884,2026-10-15,C0523,NaN,Central,Online,P010,Home,7,123.70,0.20,Card,865.90,692.72
930,T0025010,2026-07-17,C0523,Consumer,Central,Store,P020,Personal Care,2,90.49,0.25,Cash,180.98,135.73
1769,T0017550,2025-09-02,C0523,Consumer,Central,Store,P082,Sports,4,18.31,0.00,Transfer,73.24,73.24
3390,T0020300,2026-05-29,C0523,Consumer,Central,Store,P063,Electronics,4,377.12,0.00,Digital Wallet,1508.48,1508.48
4627,T0003346,2026-02-14,C0523,Consumer,Central,Marketplace,P031,Personal Care,7,31.09,0.05,Digital Wallet,217.63,206.75
4948,T0006120,2025-04-25,C0523,Consumer,Central,Store,P075,Office,1,56.91,0.00,Card,56.91,56.91
5640,T0004528,2026-12-09,C0523,Consumer,Central,Online,P013,Personal Care,2,56.17,0.05,Cash,112.34,106.72
6795,T0006328,2026-01-06,C0523,Consumer,Central,Online,P079,Home,1,31.25,0.15,Digital Wallet,31.25,26.56
7234,T0010513,2026-05-28,C0523,Consumer,Central,Online,P114,Home,1,205.30,0.10,Transfer,205.30,184.77
9397,T0001243,2026-09-15,C0523,Consumer,Central,Online,P002,Personal Care,1,60.98,0.00,Card,60.98,60.98
10503,T0001334,2025-12-06,C0523,Consumer,Central,Online,P116,Office,8,23.90,0.05,Transfer,191.20,181.64
11338,T0007462,2026-09-02,C0523,Consumer,Central,Marketplace,P016,Sports,2,39.70,0.00,Transfer,79.40,79.40
11786,T0018930,2025-05-04,C0523,Consumer,Central,Online,P074,Personal Care,2,6.16,0.00,Transfer,12.32,12.32
11854,T0006190,2026-03-03,C0523,Consumer,Central,Store,P119,Office,6,48.82,0.00,Card,292.92,292.92
12207,T0023346,2025-06-08,C0523,Consumer,Central,Store,P016,Sports,3,39.19,0.15,Card,117.57,99.93
12349,T0026593,2025-04-03,C0523,Consumer,Central,Online,P060,Personal Care,3,71.68,0.00,Cash,215.04,215.04
12670,T0021639,2026-05-21,C0523,Consumer,Central,Online,P073,Office,1,107.59,0.10,Card,107.59,96.83
13933,T0006805,2026-02-05,C0523,Consumer,Central,Online,P028,Personal Care,1,80.98,0.00,Transfer,80.98,80.98
14018,T0000042,2025-12-23,C0523,Consumer,Central,Online,P091,Sports,5,15.72,0.00,Card,78.60,78.60
14276,T0003498,2025-05-16,C0523,Consumer,Central,Store,P097,Office,7,114.10,0.25,Transfer,798.70,599.03
15025,T0023961,2026-12-22,C0523,Consumer,Central,Online,P033,Sports,2,157.28,0.20,Card,314.56,251.65
15083,T0016565,2026-02-10,C0523,Consumer,Central,Marketplace,P068,Electronics,3,222.81,0.00,Cash,668.43,668.43
16813,T0025834,2025-02-05,C0523,Consumer,Central,Store,P049,Office,4,95.36,0.00,Digital Wallet,381.44,381.44
18216,T0022818,2026-03-24,C0523,Consumer,Central,Online,P110,Electronics,3,416.79,0.00,Card,1250.37,1250.37
18806,T0027892,2025-06-08,C0523,Consumer,Central,Store,P109,Home,1,20.05,0.25,Transfer,20.05,15.04
18974,T0020361,2025-04-14,C0523,Consumer,Central,Store,P090,Electronics,1,810.42,0.00,Digital Wallet,810.42,810.42
19413,T0000158,2026-02-02,C0523,Consumer,Central,Store,P085,Home,3,159.47,0.10,Card,478.41,430.57
21361,T0013541,2026-11-10,C0523,Consumer,Central,Marketplace,P022,Home,1,154.57,0.00,Cash,154.57,154.57
22155,T0001462,2025-04-11,C0523,Consumer,Central,Store,P115,Personal Care,5,87.76,0.05,Card,438.80,416.86
22515,T0001395,2026-07-30,C0523,Consumer,Central,Online,P072,Sports,1,244.31,0.10,Card,244.31,219.88
23993,T0007368,2026-09-04,C0523,Consumer,Central,Store,P013,Personal Care,2,51.47,0.05,Card,102.94,97.79
24569,T0012284,2025-06-21,C0523,Consumer,Central,Online,P015,Home,1,66.40,0.00,Cash,66.40,66.40
25000,T0023372,2025-12-09,C0523,Consumer,Central,Online,P099,Office,2,113.66,0.00,Transfer,227.32,227.32
26284,T0011193,2026-11-16,C0523,Consumer,Central,Store,P033,Sports,4,149.09,0.00,Digital Wallet,596.36,596.36
26560,T0002230,2026-01-26,C0523,Consumer,Central,Store,P058,Personal Care,2,39.87,0.15,Cash,79.74,67.78
27492,T0008959,2025-04-26,C0523,Consumer,Central,Marketplace,P007,Electronics,3,458.87,0.10,Card,1376.61,1238.95
27927,T0019047,2026-11-17,C0523,Consumer,Central,Store,P088,Sports,2,32.78,0.20,Card,65.56,52.45

In [13]:
df.groupby('customer_id')['customer_segment'].nunique().loc[lambda x: x > 1]

Series([], Name: customer_segment, dtype: int64)

In [14]:
clientes_con_nulo = df.loc[df['customer_segment'].isna(), 'customer_id'].unique()

segmentos_por_cliente = df.groupby('customer_id')['customer_segment'].nunique()

segmentos_por_cliente.loc[clientes_con_nulo]

customer_id
C0523    1
C0754    1
C0449    1
C0797    1
C0321    1
C0753    1
C0737    1
C0279    1
C0088    1
C0042    1
C0774    1
C0211    1
C0429    1
C0457    1
C0327    1
C0203    1
C0818    1
C0120    1
C0645    1
C0367    1
C0342    1
C0680    1
C0235    1
C0297    1
C0533    1
C0030    1
C0226    1
C0302    1
C0846    1
C0705    1
C0101    1
C0558    1
C0221    1
C0171    1
C0141    1
C0328    1
C0667    1
C0027    1
Name: customer_segment, dtype: int64

In [15]:
segmento_por_cliente = df.groupby('customer_id')['customer_segment'].first()

In [16]:
segmento_por_cliente.head()

customer_id
C0001          SMB
C0002     Consumer
C0003    Corporate
C0004          SMB
C0005     Consumer
Name: customer_segment, dtype: str

In [17]:
df['customer_id'].head()

0    C0222
1    C0590
2    C0827
3    C0130
4    C0234
Name: customer_id, dtype: str

In [18]:
df['customer_id'].map(segmento_por_cliente).head()

0    Consumer
1    Consumer
2         SMB
3         SMB
4         SMB
Name: customer_id, dtype: str

In [19]:
segmento_por_cliente.loc['C0222']

'Consumer'

In [20]:
df['customer_segment'] = df['customer_segment'].fillna(df['customer_id'].map(segmento_por_cliente))

In [21]:
df['customer_segment'].isna().sum()

np.int64(0)

In [22]:
region_por_cliente = df.groupby('customer_id')['region'].nunique().loc[lambda x: x > 1]
region_por_cliente

Series([], Name: region, dtype: int64)

In [23]:
region_con_nulo = df.loc[df['region'].isna(), 'customer_id'].unique()

region_por_cliente = df.groupby('customer_id')['region'].nunique()

region_por_cliente.loc[region_con_nulo]

customer_id
C0693    1
C0304    1
C0788    1
C0357    1
C0441    1
C0187    1
C0436    1
C0707    1
C0476    1
C0301    1
C0222    1
C0004    1
C0613    1
C0351    1
C0486    1
C0508    1
C0299    1
C0610    1
C0626    1
C0025    1
C0387    1
C0530    1
C0670    1
C0423    1
C0023    1
C0017    1
C0090    1
Name: region, dtype: int64

In [24]:
region_cliente = df.groupby('customer_id')['region'].first()
region_cliente.head()

customer_id
C0001    North
C0002    North
C0003     West
C0004     West
C0005    North
Name: region, dtype: str

In [25]:
df['region'] = df['region'].fillna(df['customer_id'].map(region_cliente))
df['region'].isna().sum()

np.int64(0)

In [26]:
metodos_de_pago = df.groupby('customer_id')['payment_method'].nunique().loc[lambda x: x > 1]
metodos_de_pago

customer_id
C0001    4
C0002    4
C0003    4
C0004    4
C0005    4
        ..
C0846    4
C0847    4
C0848    4
C0849    4
C0850    4
Name: payment_method, Length: 850, dtype: int64

In [27]:
df['payment_method'] = df['payment_method'].fillna('Unknown')
df.isna().sum()

transaction_id      0
transaction_date    0
customer_id         0
customer_segment    0
region              0
channel             0
product_id          0
category            0
units               0
unit_price          0
discount_pct        0
payment_method      0
gross_revenue       0
net_revenue         0
dtype: int64

In [28]:
df[df.duplicated(subset=['transaction_id'], keep=False)].sort_values(by='transaction_id')

,transaction_id,transaction_date,customer_id,customer_segment,region,channel,product_id,category,units,unit_price,discount_pct,payment_method,gross_revenue,net_revenue
1296,T0000755,2025-10-24,C0087,SMB,West,Online,P076,Office,2,37.18,0.00,Digital Wallet,74.36,74.36
21200,T0000755,2025-10-24,C0087,SMB,West,Online,P076,Office,2,37.18,0.00,Digital Wallet,74.36,74.36
721,T0000879,2026-03-23,C0385,Consumer,North,Store,P002,Personal Care,2,59.31,0.00,Card,118.62,118.62
14183,T0000879,2026-03-23,C0385,Consumer,North,Store,P002,Personal Care,2,59.31,0.00,Card,118.62,118.62
424,T0000906,2025-03-15,C0306,Consumer,North,Marketplace,P058,Personal Care,2,37.03,0.05,Card,74.06,70.36
15917,T0000906,2025-03-15,C0306,Consumer,North,Marketplace,P058,Personal Care,2,37.03,0.05,Card,74.06,70.36
26645,T0002141,2026-01-22,C0220,Consumer,Central,Online,P038,Electronics,3,326.23,0.15,Cash,978.69,831.89
23635,T0002141,2026-01-22,C0220,Consumer,Central,Online,P038,Electronics,3,326.23,0.15,Cash,978.69,831.89
16238,T0008607,2026-05-10,C0143,Corporate,South,Online,P097,Office,3,121.68,0.15,Card,365.04,310.28
942,T0008607,2026-05-10,C0143,Corporate,South,Online,P097,Office,3,121.68,0.15,Card,365.04,310.28
9454,T0008812,2026-10-24,C0543,SMB,North,Online,P108,Office,3,123.87,0.00,Card,371.61,371.61
3960,T0008812,2026-10-24,C0543,SMB,North,Online,P108,Office,3,123.87,0.00,Card,371.61,371.61
3340,T0009119,2025-03-19,C0199,Consumer,West,Online,P063,Electronics,4,412.44,0.00,Transfer,1649.76,1649.76
2078,T0009119,2025-03-19,C0199,Consumer,West,Online,P063,Electronics,4,412.44,0.00,Transfer,1649.76,1649.76
25197,T0010486,2026-07-14,C0587,Consumer,North,Store,P093,Electronics,4,825.49,0.20,Card,3301.96,2641.57
15070,T0010486,2026-07-14,C0587,Consumer,North,Store,P093,Electronics,4,825.49,0.20,Card,3301.96,2641.57
19465,T0013042,2026-10-11,C0782,Corporate,West,Marketplace,P077,Sports,3,205.94,0.00,Transfer,617.82,617.82
11524,T0013042,2026-10-11,C0782,Corporate,West,Marketplace,P077,Sports,3,205.94,0.00,Transfer,617.82,617.82
8512,T0013112,2025-12-09,C0448,SMB,North,Online,P092,Home,7,58.02,0.20,Card,406.14,324.91
3111,T0013112,2025-12-09,C0448,SMB,North,Online,P092,Home,7,58.02,0.20,Card,406.14,324.91
14221,T0018216,2025-06-26,C0382,Corporate,Central,Online,P043,Electronics,4,872.36,0.00,Cash,3489.44,3489.44
15632,T0018216,2025-06-26,C0382,Corporate,Central,Online,P043,Electronics,4,872.36,0.00,Cash,3489.44,3489.44
22970,T0019598,2026-11-25,C0308,SMB,North,Store,P090,Electronics,3,766.70,0.10,Transfer,2300.10,2070.09
27650,T0019598,2026-11-25,C0308,SMB,North,Store,P090,Electronics,3,766.70,0.10,Transfer,2300.10,2070.09
16591,T0019748,2026-03-12,C0849,Consumer,West,Online,P096,Home,1,64.96,0.25,Card,64.96,48.72
6021,T0019748,2026-03-12,C0849,Consumer,West,Online,P096,Home,1,64.96,0.25,Card,64.96,48.72
16316,T0021563,2025-11-04,C0185,SMB,Central,Store,P015,Home,5,59.44,0.00,Digital Wallet,297.20,297.20
9404,T0021563,2025-11-04,C0185,SMB,Central,Store,P015,Home,5,59.44,0.00,Digital Wallet,297.20,297.20
14930,T0022587,2026-10-13,C0388,Corporate,Central,Store,P059,Personal Care,6,63.46,0.10,Transfer,380.76,342.68
10779,T0022587,2026-10-13,C0388,Corporate,Central,Store,P059,Personal Care,6,63.46,0.10,Transfer,380.76,342.68
18614,T0023816,2025-11-18,C0177,Consumer,West,Store,P089,Personal Care,1,98.94,0.00,Cash,98.94,98.94
21816,T0023816,2025-11-18,C0177,Consumer,West,Store,P089,Personal Care,1,98.94,0.00,Cash,98.94,98.94
13567,T0026555,2025-11-12,C0253,Consumer,South,Store,P003,Home,1,140.44,0.10,Transfer,140.44,126.40
16700,T0026555,2025-11-12,C0253,Consumer,South,Store,P003,Home,1,140.44,0.10,Transfer,140.44,126.40
6747,T0027253,2025-02-19,C0439,SMB,Central,Online,P107,Electronics,3,330.66,0.00,Cash,991.98,991.98
25661,T0027253,2025-02-19,C0439,SMB,Central,Online,P107,Electronics,3,330.66,0.00,Cash,991.98,991.98

In [29]:
print("Filas:", len(df))
print("IDs únicos:", df['transaction_id'].nunique())
print("Duplicados completos:", df.duplicated().sum())
print("IDs extra:", len(df) - df['transaction_id'].nunique())

Filas: 28018
IDs únicos: 28000
Duplicados completos: 18
IDs extra: 18

In [30]:
df.duplicated(subset=['transaction_id']).sum()

np.int64(18)

In [31]:
df.drop_duplicates(subset=['transaction_id'], keep='first', inplace=True)

In [32]:
print("Filas:", len(df))
print("IDs únicos:", df['transaction_id'].nunique())
print("IDs duplicados:", df.duplicated(subset=['transaction_id']).sum())

Filas: 28000
IDs únicos: 28000
IDs duplicados: 0

In [33]:
df['transaction_date'].head()

0    2026-11-01
1    2025-06-01
2    2026-10-24
3    2025-04-18
4    2025-11-15
Name: transaction_date, dtype: str

In [34]:
print("Fecha mínima:", df['transaction_date'].min())
print("Fecha máxima:", df['transaction_date'].max())

Fecha mínima: 2025-01-01
Fecha máxima: 2026-12-31

In [35]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'], format='%Y-%m-%d')
df['transaction_date'].head()

0   2026-11-01
1   2025-06-01
2   2026-10-24
3   2025-04-18
4   2025-11-15
Name: transaction_date, dtype: datetime64[us]

In [36]:
df['transaction_date'].dt.year.head()

0    2026
1    2025
2    2026
3    2025
4    2025
Name: transaction_date, dtype: int32

In [37]:
df['transaction_date'].dt.month.head()

0    11
1     6
2    10
3     4
4    11
Name: transaction_date, dtype: int32

In [38]:
df.describe()

,transaction_date,units,unit_price,discount_pct,gross_revenue,net_revenue
count,28000,28000.000000,28000.000000,28000.000000,28000.000000,28000.000000
mean,2026-03-04 09:44:07.542857,2.844536,175.671470,0.062621,503.558166,471.860535
min,2025-01-01 00:00:00,0.000000,-318.740000,0.000000,5.830000,4.560000
25%,2025-09-28 00:00:00,1.000000,57.290000,0.000000,111.057500,103.647500
50%,2026-04-02 00:00:00,2.000000,115.860000,0.050000,256.000000,239.035000
75%,2026-08-26 00:00:00,4.000000,212.990000,0.100000,591.450000,553.855000
max,2026-12-31 00:00:00,8.000000,952.200000,0.250000,7266.000000,6822.080000
std,NaN,1.884692,181.183762,0.075180,716.362282,672.479349

In [40]:
(df['units'] <=0).sum()

np.int64(12)

In [41]:
(df['unit_price'] <= 0).sum()

np.int64(6)

In [47]:
df[(df['units'] <= 0) | (df['unit_price'] <= 0)]

,transaction_id,transaction_date,customer_id,customer_segment,region,channel,product_id,category,units,unit_price,discount_pct,payment_method,gross_revenue,net_revenue
1155,T0007985,2025-06-01,C0726,Consumer,Central,Marketplace,P009,Personal Care,0,110.56,0.00,Digital Wallet,221.12,221.12
1842,T0001304,2025-12-27,C0760,Consumer,Central,Store,P085,Home,4,-159.96,0.00,Transfer,639.84,639.84
3541,T0011379,2026-10-18,C0324,Consumer,South,Store,P063,Electronics,0,391.10,0.00,Card,782.20,782.20
6462,T0017126,2025-06-21,C0146,Consumer,Central,Store,P100,Office,2,-178.40,0.00,Digital Wallet,356.80,356.80
9488,T0018135,2025-10-18,C0499,Consumer,Central,Marketplace,P096,Home,0,67.52,0.00,Card,67.52,67.52
10620,T0007082,2025-11-14,C0023,Corporate,West,Marketplace,P095,Personal Care,0,20.37,0.00,Card,40.74,40.74
12683,T0013036,2026-09-28,C0759,Consumer,Central,Store,P031,Personal Care,0,31.74,0.00,Digital Wallet,31.74,31.74
13967,T0021882,2025-06-10,C0089,Consumer,West,Store,P014,Personal Care,0,25.86,0.00,Transfer,77.58,77.58
14133,T0005176,2026-12-30,C0580,Consumer,Central,Store,P036,Sports,2,-318.74,0.00,Digital Wallet,637.48,637.48
14609,T0026084,2025-05-25,C0615,Consumer,South,Store,P093,Electronics,0,790.74,0.15,Digital Wallet,2372.22,2016.39
15779,T0010894,2025-12-18,C0467,SMB,Central,Online,P098,Home,3,-191.74,0.15,Digital Wallet,575.22,488.94
16366,T0025955,2025-11-04,C0131,Consumer,West,Store,P094,Sports,0,186.55,0.10,Card,746.20,671.58
18241,T0017769,2025-05-16,C0634,Consumer,Central,Online,P117,Sports,2,-148.50,0.05,Card,297.00,282.15
19613,T0006381,2025-11-20,C0154,SMB,North,Online,P091,Sports,0,15.84,0.00,Card,63.36,63.36
19723,T0017629,2026-07-06,C0715,SMB,South,Store,P044,Personal Care,0,63.83,0.00,Cash,255.32,255.32
22547,T0002593,2025-11-29,C0382,Corporate,Central,Online,P084,Electronics,0,194.67,0.15,Transfer,1557.36,1323.76
23801,T0002677,2026-01-17,C0121,SMB,Central,Store,P114,Home,3,-218.66,0.05,Card,655.98,623.18
27360,T0004122,2025-06-08,C0609,SMB,West,Online,P017,Home,0,14.41,0.00,Card,14.41,14.41

In [48]:
df.loc[df['units'] <= 0,['transaction_id', 'units', 'unit_price', 'gross_revenue']]

      transaction_id  units  unit_price  gross_revenue
1155        T0007985      0      110.56         221.12
3541        T0011379      0      391.10         782.20
9488        T0018135      0       67.52          67.52
10620       T0007082      0       20.37          40.74
12683       T0013036      0       31.74          31.74
13967       T0021882      0       25.86          77.58
14609       T0026084      0      790.74        2372.22
16366       T0025955      0      186.55         746.20
19613       T0006381      0       15.84          63.36
19723       T0017629      0       63.83         255.32
22547       T0002593      0      194.67        1557.36
27360       T0004122      0       14.41          14.41

In [49]:
df.loc[df['units'] <= 0, 'gross_revenue'] / df.loc[df['units'] <= 0, 'unit_price']

1155     2.0
3541     2.0
9488     1.0
10620    2.0
12683    1.0
13967    3.0
14609    3.0
16366    4.0
19613    4.0
19723    4.0
22547    8.0
27360    1.0
dtype: float64

In [55]:
df.loc[df['units'] <= 0, 'units'] = (df.loc[df['units'] <= 0, 'gross_revenue'] / df.loc[df['units'] <= 0, 'unit_price']).astype('int64')

In [56]:
(df['units'] <= 0).sum()

np.int64(0)

In [57]:
df.loc[df['unit_price'] <= 0, ['transaction_id', 'units', 'unit_price', 'gross_revenue', 'net_revenue', 'discount_pct']]

,transaction_id,units,unit_price,gross_revenue,net_revenue,discount_pct
1842,T0001304,4,-159.96,639.84,639.84,0.00
6462,T0017126,2,-178.40,356.80,356.80,0.00
14133,T0005176,2,-318.74,637.48,637.48,0.00
15779,T0010894,3,-191.74,575.22,488.94,0.15
18241,T0017769,2,-148.50,297.00,282.15,0.05
23801,T0002677,3,-218.66,655.98,623.18,0.05

In [58]:
df.loc[df['unit_price'] <= 0, 'unit_price'] = df.loc[df['unit_price'] <= 0, 'unit_price'].abs()

In [59]:
(df['unit_price'] <= 0).sum()

np.int64(0)